on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NO_ACCESS }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NO_ACCESS }}
        aws-region: us-east-2

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@master
      with:
        task-definition: task-definition.json
        service: sample-app-service
        cluster: default
        wait-for-service-stability: true
